
"""Original, now outdated ideas as of 3/11/2025, but can add more to this list later:
- real excerpts from classic literature (i.e. a poem, a short story, or novel, including anything commonly taught in English I, II, II, IV, or AP Literature or Language, as well as works by Homer, Shakespeare, Austen, Dickens, Dostoevsky, Tolstoy, as well as other popular and lesser known authors)
                        - historical events, leaders, and movements (i.e. excerpts from historical documents, speeches, or books about real historical figures and events in American, European, or world history)
                        - real studies or experiments in social studies (economics, psychology, sociology, anthropology, etc.) 
                        - real studies or experiments in hard sciences (physics, chemistry, biology, etc.)
                        - real technology, business, or finance (i.e. excerpts from business magazines, articles, or books about real startups, companies, or industries)
                        - art, music, film, fashion, or sports (i.e. descriptions of pieces created or events/movements in famous artworks, movies, songs, athletes, or fashion designers)
                        - philosophy, ethics, or political science (i.e. excerpts from Federalist Papers, iconic Supreme Court cases, famous philosophers' works like Plato, Aristotle, Kant, Kierkegaard, Hume, Camus, and other cultures' philosophers, etc.)
                        - current events and pop culture (i.e. excerpts from popular news sources, social media, or cultural references)
"""

literatureTopics = [
  "Hester Prynne’s public shaming in The Scarlet Letter",
  "Jay Gatsby’s pursuit of the American Dream in The Great Gatsby",
  "The creature’s longing for acceptance in Frankenstein",
  "Okonkwo’s struggle with cultural change in Things Fall Apart",
  "Santiago’s perseverance in The Old Man and the Sea",
  "The conflict between science and morality in Dr. Jekyll and Mr. Hyde",
  "Holden Caulfield’s cynicism and isolation in The Catcher in the Rye",
  "Celie’s journey to self-empowerment in The Color Purple",
  "Sethe’s haunting past in Beloved",
  "Atticus Finch’s defense of Tom Robinson in To Kill a Mockingbird",
  "Macbeth’s ambition and descent into tyranny in Macbeth",
  "Winston Smith’s internal rebellion in 1984",
  "The hypocrisy of religious figures in The Canterbury Tales",
  "Gregor Samsa’s alienation in The Metamorphosis",
  "The struggle between individual conscience and societal expectations in Antigone",
  "The impact of colonialism in Heart of Darkness",
  "Meursault’s existential indifference in The Stranger",
  "The plight of migrant workers in The Grapes of Wrath",
  "The symbolism of Miss Havisham’s decayed wedding dress in Great Expectations",
  "Heathcliff’s obsession and revenge in Wuthering Heights",
  "The psychological torment of Roderick Usher in The Fall of the House of Usher",
  "Janey Crawford’s search for independence in Their Eyes Were Watching God",
  "Tom Wingfield’s longing for escape in The Glass Menagerie",
  "Esteban Trueba’s political transformation in The House of the Spirits",
  "Emma Bovary’s romantic illusions and downfall in Madame Bovary",
  "The contrasting worldviews of Pangloss and Candide in Candide",
  "The power dynamics in Prospero’s rule over Caliban in The Tempest",
  "Jean Valjean’s moral redemption in Les Misérables",
  "Ralph’s leadership struggles in Lord of the Flies",
  "The existential themes in The Trial by Franz Kafka",
  "The moral dilemmas in Crime and Punishment by Fyodor Dostoevsky",
  "The satire of totalitarianism in Animal Farm by George Orwell",
  "The racial tensions and injustice in Native Son by Richard Wright",
  "The feminist perspective in The Handmaid’s Tale by Margaret Atwood",
  "The impact of war on the human psyche in All Quiet on the Western Front",
  "The themes of alienation and identity in Invisible Man by Ralph Ellison",
  "The depiction of morality in The Picture of Dorian Gray by Oscar Wilde",
  "The themes of class struggle in A Tale of Two Cities by Charles Dickens",
  "The exploration of destiny and free will in Oedipus Rex by Sophocles",
  "The quest for meaning in Siddhartha by Hermann Hesse",
  "The role of fate in Tess of the d’Urbervilles by Thomas Hardy",
  "The influence of nature in Walden by Henry David Thoreau",
  "The impact of industrialization in Hard Times by Charles Dickens",
  "The conflicts between passion and reason in Wuthering Heights",
  "The power of storytelling in Life of Pi by Yann Martel",
  "The depiction of loneliness in Of Mice and Men by John Steinbeck",
  "The critique of materialism in The Great Gatsby",
  "The role of honor and reputation in Othello by William Shakespeare",
  "The corruption of power in Julius Caesar by William Shakespeare",
  "The contrast between civilization and savagery in Lord of the Flies",
  "The philosophical dilemmas in No Exit by Jean-Paul Sartre",
  "The critique of colonialism in Things Fall Apart",
  "The psychological depth of Raskolnikov in Crime and Punishment",
  "The role of fate in Shakespeare’s Romeo and Juliet",
  "The portrayal of war in The Red Badge of Courage",
  "The impact of racism in To Kill a Mockingbird",
  "The role of magic realism in One Hundred Years of Solitude",
  "The theme of free will in Slaughterhouse-Five",
  "The critique of bureaucracy in Catch-22",
  "The symbolism of the green light in The Great Gatsby",
  "The dystopian elements in Fahrenheit 451",
  "The power struggle in A Streetcar Named Desire",
  "The clash of cultures in The Joy Luck Club",
  "The role of women in The House of Mirth",
  "The psychological depth of Hamlet in Hamlet",
  "The existential themes in The Stranger by Albert Camus",
  "The journey motif in The Odyssey",
  "The significance of the mockingbird in To Kill a Mockingbird",
  "The use of stream of consciousness in Mrs. Dalloway",
  "The allegory of power in The Lord of the Rings",
  "The impact of industrialization in The Jungle by Upton Sinclair",
  "The critique of romantic ideals in Anna Karenina",
  "The coming-of-age journey in The Catcher in the Rye",
  "The representation of the American Dream in Death of a Salesman",
  "The tragic downfall of Gatsby in The Great Gatsby",
  "The role of prophecy in Macbeth",
  "The interplay of light and dark imagery in Heart of Darkness",
  "The influence of Gothic elements in Dracula",
  "The moral ambiguity in The Scarlet Letter",
  "The theme of survival in The Road by Cormac McCarthy",
  "The existential search for meaning in The Plague by Albert Camus",
  "The examination of trauma in Bel Canto by Ann Patchett",
  "The complexities of war in A Long Way Gone by Ishmael Beah",
  "The moral decay in Never Let Me Go by Kazuo Ishiguro",
  "The critique of capitalism in White Noise by Don DeLillo",
  "The social constraints on women in The Awakening by Kate Chopin",
  "The clash of tradition and change in Snow by Orhan Pamuk",
  "The haunting past in The Shadow of the Wind by Carlos Ruiz Zafón",
  "The self-actualization journey in The Namesake by Jhumpa Lahiri",
  "The complexity of family dynamics in Everything I Never Told You by Celeste Ng",
  "The exploration of power in The Secret History by Donna Tartt",
  "The portrayal of grief in A Little Life by Hanya Yanagihara",
  "The unraveling of identity in The Woman in the Dunes by Kobo Abe",
  "The resilience of women in The Color of Water by James McBride",
  "The burden of history in Pachinko by Min Jin Lee",
  "The philosophical musings in If on a Winter's Night a Traveler by Italo Calvino",
  "The examination of race and identity in The Vanishing Half by Brit Bennett",
  "The moral and ethical conflicts in The Remains of the Day by Kazuo Ishiguro",
  "The struggle of indigenous identity in There There by Tommy Orange",
  "The impact of political oppression in The Sympathizer by Viet Thanh Nguyen",
  "The supernatural and folklore in The Snow Child by Eowyn Ivey",
  "The exploration of human fragility in We the Animals by Justin Torres",
  "The psychological depth in The Bell Jar by Sylvia Plath",
  "The consequences of colonialism in Season of Migration to the North by Tayeb Salih",
  "The journey of cultural identity in Americanah by Chimamanda Ngozi Adichie",
  "The impact of war on civilians in The Kite Runner by Khaled Hosseini",
  "The feminist perspective in The Yellow Wallpaper by Charlotte Perkins Gilman",
  "The exploration of destiny and free will in The Master and Margarita by Mikhail Bulgakov",
  "The theme of memory in The Housekeeper and the Professor by Yoko Ogawa",
  "The tension between tradition and modernity in The Inheritance of Loss by Kiran Desai",
  "The search for truth and justice in Disgrace by J.M. Coetzee",
  "The brutality of war in Half of a Yellow Sun by Chimamanda Ngozi Adichie",
  "The loss of innocence in The Ocean at the End of the Lane by Neil Gaiman",
  "The conflicts of faith and doubt in Silence by Shūsaku Endō",
  "The impact of migration on identity in Behold the Dreamers by Imbolo Mbue",
  "The navigation of love and loss in Call Me by Your Name by André Aciman",
  "The critique of media culture in The Circle by Dave Eggers",
  "The power of storytelling in The Book Thief by Markus Zusak",
  "The clash of Eastern and Western values in The Joy Luck Club by Amy Tan",
  "The dystopian warning in The Power by Naomi Alderman",
  "The exploration of queerness in Giovanni's Room by James Baldwin",
  "The burden of family expectations in The Leavers by Lisa Ko",
  "The existential questions in The Meursault Investigation by Kamel Daoud",
  "The beauty of language in The Shadow Lines by Amitav Ghosh",
  "The interwoven destinies in The Night Circus by Erin Morgenstern",
  "The complexity of relationships in Normal People by Sally Rooney",
  "The magic realism of Like Water for Chocolate by Laura Esquivel",
  "The role of fate in The Bone Clocks by David Mitchell",
  "The social struggles in The Nickel Boys by Colson Whitehead",
  "The fragmentation of memory in Lost Children Archive by Valeria Luiselli",
  "The poetic retelling of myth in Circe by Madeline Miller",
  "The consequences of revenge in Home Fire by Kamila Shamsie",
  "The role of ambition and downfall in The Queen’s Gambit by Walter Tevis",
  "The cultural heritage in The Moor’s Account by Laila Lalami",
  "The psychological realism in The Door by Magda Szabó",
  "The lasting effects of trauma in My Dark Vanessa by Kate Elizabeth Russell",
  "The post-colonial tensions in The God of Small Things by Arundhati Roy",
  "The intricate family drama in The Lowland by Jhumpa Lahiri",
  "The generational saga in The House of the Spirits by Isabel Allende",
  "The science fiction allegory in Kindred by Octavia Butler",
  "The examination of artificial intelligence in Klara and the Sun by Kazuo Ishiguro",
  "The influence of mythology in The Song of Achilles by Madeline Miller",
  "The impact of environmental destruction in The Overstory by Richard Powers",
  "The portrayal of isolation in Convenience Store Woman by Sayaka Murata",
  "The themes of grief and survival in The Light Between Oceans by M.L. Stedman",
  "The impact of political unrest in Persepolis by Marjane Satrapi",
  "The struggle of immigrants in The Buddha in the Attic by Julie Otsuka",
  "The examination of trauma in The Fifth Season by N.K. Jemisin",
  "The role of storytelling in The Storyteller by Jodi Picoult",
  "The intergenerational conflict in The Hundred Secret Senses by Amy Tan",
  "The examination of loneliness in Eleanor Oliphant Is Completely Fine by Gail Honeyman",
  "The clash of cultures in The Beekeeper of Aleppo by Christy Lefteri",
  "The political allegory in Exit West by Mohsin Hamid",
  "The haunting portrayal of regret in The Sense of an Ending by Julian Barnes",
  "The critique of social class in Small Great Things by Jodi Picoult",
  "The magical realism of One Hundred Shadows by Hwang Jungeun"
];

historyTopics = [
  "The impact of the Emancipation Proclamation on the Civil War",
  "The significance of the Louisiana Purchase in U.S. expansion",
  "The causes and effects of the Great Depression",
  "The influence of the Enlightenment on the American Revolution",
  "The role of the Marshall Plan in post-World War II Europe",
  "The civil rights movement and the impact of the Voting Rights Act of 1965",
  "The ideological conflict between capitalism and communism in the Cold War",
  "The impact of the Industrial Revolution on urbanization and labor",
  "The significance of the Seneca Falls Convention in women's rights history",
  "The role of the Treaty of Versailles in shaping World War II",
  "The legacy of the Magna Carta in shaping constitutional government",
  "The impact of the Columbian Exchange on world economies and cultures",
  "The causes and consequences of the fall of the Roman Empire",
  "The effects of the Black Death on medieval Europe",
  "The influence of the printing press on the Protestant Reformation",
  "The role of nationalism in the unification of Germany and Italy",
  "The significance of the Monroe Doctrine in U.S. foreign policy",
  "The causes and consequences of the Indian Removal Act",
  "The importance of the Harlem Renaissance in shaping American culture",
  "The impact of the Meiji Restoration on Japan’s modernization",
  "The role of the transcontinental railroad in American westward expansion",
  "The effects of imperialism on Africa and Asia in the 19th century",
  "The significance of Brown v. Board of Education in desegregation",
  "The impact of the Cold War on space exploration",
  "The influence of the New Deal on government economic policy",
  "The role of women in the workforce during World War II",
  "The causes and effects of the Boston Tea Party",
  "The significance of the Battle of Gettysburg in the Civil War",
  "The role of the Persian Empire in shaping early global trade",
  "The effects of the Napoleonic Wars on European politics",
  "The contributions of the Harlem Hellfighters in World War I",
  "The impact of the Manhattan Project on global warfare",
  "The role of the Suffragette movement in securing voting rights",
  "The expansion of the Mongol Empire and its global impact",
  "The consequences of the Space Race between the U.S. and USSR",
  "The significance of the Arab Spring on modern Middle Eastern politics",
  "The influence of the Treaty of Westphalia on modern nation-states",
  "The rise and fall of the Ottoman Empire",
  "The impact of the Agricultural Revolution on human societies",
  "The historical context and impact of the Tiananmen Square protests",
  "The impact of the Silk Road on trade and cultural exchange",
  "The influence of the Renaissance on modern thought",
  "The expansion and collapse of the Soviet Union",
  "The effects of the Crusades on European and Middle Eastern relations",
  "The significance of the Louisiana Purchase in shaping the U.S.",
  "The causes and consequences of the Boxer Rebellion",
  "The influence of the Scientific Revolution on global development",
  "The rise of totalitarian regimes in the 20th century",
  "The impact of the printing press on literacy and knowledge",
  "The role of the Haitian Revolution in anti-colonial movements",
  "The economic and social effects of the Great Migration",
  "The legacy of the Mayflower Compact in U.S. democracy",
  "The rise and fall of feudalism in medieval Europe",
  "The political philosophy of the Founding Fathers",
  "The effects of European colonization on Indigenous populations",
  "The causes and outcomes of the Glorious Revolution in England",
  "The Cold War’s influence on proxy wars around the world",
  "The role of women in the American Revolutionary War",
  "The significance of D-Day in World War II",
  "The impact of McCarthyism on American society",
  "The geopolitical consequences of the Berlin Airlift",
  "The role of propaganda in World War I",
  "The environmental impact of the Industrial Revolution",
  "The influence of Islamic Golden Age scholars on modern science",
  "The rise of globalism in the 21st century",
  "The impact of the Treaty of Ghent on U.S.-British relations",
  "The historical significance of the California Gold Rush",
  "The role of Nelson Mandela in dismantling apartheid",
  "The effects of the Opium Wars on China’s sovereignty",
  "The influence of the Greek and Roman republics on modern democracies"
];



socialScienceTopics = [
  "The Stanford Prison Experiment and its implications on authority and power",
  "The Marshmallow Test and delayed gratification in childhood development",
  "The Hawthorne Effect and workplace productivity",
  "The Milgram Experiment on obedience to authority",
  "The Bystander Effect and its role in social responsibility",
  "The Pygmalion Effect and self-fulfilling prophecies in education",
  "The Tragedy of the Commons and shared resource depletion",
  "The Broken Windows Theory and crime prevention strategies",
  "The Asch Conformity Experiment and peer pressure",
  "The effects of implicit bias on decision-making",
  "The Robbers Cave Experiment and intergroup conflict",
  "The Rosenthal Effect and its impact on student performance",
  "Cognitive dissonance and how people reconcile conflicting beliefs",
  "The Social Learning Theory and the role of modeling in behavior",
  "The impact of stereotype threat on academic performance",
  "The concept of cultural capital in social mobility",
  "The diffusion of responsibility in group settings",
  "The placebo effect and its implications for psychology and medicine",
  "Prospect Theory and decision-making under risk",
  "The impact of nudge theory in public policy and economics",
  "The differences between collectivist and individualist cultures",
  "The Just-World Hypothesis and victim blaming",
  "The Prisoner’s Dilemma and cooperation in game theory",
  "The Fundamental Attribution Error in everyday judgments",
  "How loss aversion affects financial decisions",
  "The concept of social proof in marketing and influence",
  "The role of cognitive biases in shaping political opinions",
  "The impact of gentrification on urban communities",
  "How microaggressions shape everyday interactions",
  "Social identity theory and group-based discrimination",
  "The Matthew Effect and cumulative advantage in education and wealth",
  "The role of emotional intelligence in workplace success",
  "The differences between implicit and explicit attitudes",
  "Behavioral economics and its influence on financial decisions",
  "How childhood attachment styles shape adult relationships",
  "The impact of mass media on public perception and fear",
  "The concept of thin-slicing in rapid judgment making",
  "The role of status anxiety in modern consumer culture",
  "How intersectionality shapes experiences of discrimination",
  "The effects of urban sprawl on social and economic inequality",
  "How learned helplessness affects motivation and performance",
  "The theory of planned behavior and predicting human action",
  "The impact of technology on socialization and human interaction",
  "The role of framing effects in shaping decision-making",
  "How groupthink contributes to poor decision-making in organizations",
  "The psychology of scarcity and its impact on poverty",
  "The impact of contact hypothesis in reducing prejudice",
  "How personality traits correlate with leadership styles",
  "The role of cultural hegemony in maintaining power structures",
  "The influence of historical trauma on marginalized communities",
  "How media framing affects perceptions of crime and violence",
  "The role of bystander intervention training in crisis situations",
  "The psychological roots of conspiracy theories",
  "How time perception affects decision-making and goal setting",
  "The role of schemas in memory and cognition",
  "How social networks influence political polarization",
  "The impact of meritocracy myths on upward mobility",
  "The psychological impact of unemployment on identity and self-worth",
  "The role of childhood socioeconomic status in shaping adult health",
  "How cultural diffusion shapes globalization and identity",
  "The impact of generational differences on workplace dynamics",
  "How scarcity mindset affects long-term planning and success",
  "The role of prosocial behavior in community-building",
  "The relationship between social stratification and access to education",
  "How moral licensing affects ethical decision-making",
  "The impact of labeling theory on criminal behavior",
  "The psychology of persuasion and compliance techniques",
  "How self-determination theory explains motivation",
  "The role of emotional contagion in group behavior"
];

hardScienceTopics = [
  "The Michelson-Morley Experiment and the discovery of special relativity",
  "The double-slit experiment and quantum mechanics",
  "The Miller-Urey Experiment and the origins of life",
  "The discovery of the DNA double helix by Watson and Crick",
  "The photoelectric effect and Einstein’s contributions to physics",
  "The discovery of penicillin and its impact on medicine",
  "The laws of thermodynamics and their applications",
  "The development of CRISPR and its role in gene editing",
  "The Large Hadron Collider and the search for the Higgs boson",
  "The evolution of antibiotic resistance in bacteria",
  "The Doppler effect and its applications in astronomy",
  "The discovery of exoplanets and their significance",
  "The human genome project and its impact on genetics",
  "The role of neurotransmitters in brain function",
  "The principles of electromagnetism and Maxwell’s equations",
  "The structure and function of ribosomes in protein synthesis",
  "The study of dark matter and dark energy in cosmology",
  "The relationship between quantum entanglement and teleportation",
  "The effects of climate change on marine ecosystems",
  "The role of epigenetics in gene expression and inheritance",
  "The chemistry behind superconductors and their applications",
  "The origin of the elements in the universe through nucleosynthesis",
  "The biomechanics of human locomotion and movement",
  "The study of gravitational waves and their detection",
  "The relationship between biodiversity and ecosystem stability",
  "The role of prions in neurodegenerative diseases",
  "The properties of graphene and its potential applications",
  "The chemistry of photosynthesis and its importance in life on Earth",
  "The concept of absolute zero and its implications for physics",
  "The effect of microgravity on the human body in space",
  "The evolution of viruses and their impact on human health",
  "The importance of water’s unique properties in sustaining life",
  "The role of quantum computing in advancing technology",
  "The impact of radiation on genetic mutations and evolution",
  "The concept of chaos theory and its applications",
  "The development of artificial intelligence and neural networks",
  "The study of ocean currents and their effects on climate",
  "The role of mitochondria in cellular respiration",
  "The impact of plastic pollution on marine life",
  "The future of renewable energy and battery technology",
  "The effects of prolonged space travel on human physiology",
  "The search for extraterrestrial life and habitable exoplanets",
  "The chemistry of combustion and fuel efficiency",
  "The role of catalysts in speeding up chemical reactions",
  "The physics behind black holes and event horizons",
  "The concept of entropy and its role in the universe",
  "The effects of ionizing radiation on biological tissue",
  "The molecular basis of cancer and targeted therapies",
  "The genetic basis of hereditary diseases and gene therapy"
];

businessTechnologyTopics = [
  "The rise and fall of Enron and corporate fraud",
  "The impact of Amazon’s supply chain innovation",
  "The founding and growth of Tesla in the electric vehicle market",
  "The dot-com bubble and its lessons for tech startups",
  "The role of venture capital in Silicon Valley startups",
  "The disruptive impact of fintech on traditional banking",
  "The role of blockchain in securing digital transactions",
  "How digital advertising transformed modern marketing",
  "The significance of IPOs in corporate expansion",
  "The effect of globalization on multinational corporations",
  "The importance of leadership styles in corporate success",
  "How gig economy platforms changed workforce dynamics",
  "The evolution of artificial intelligence in financial markets",
  "The role of government regulations in shaping tech companies",
  "The impact of automation on the job market",
  "The growth of e-commerce and its impact on retail stores",
  "The influence of behavioral economics in consumer spending",
  "The role of corporate social responsibility in brand reputation",
  "The development and rise of decentralized finance (DeFi)",
  "The history and future of cryptocurrency adoption",
  "How interest rates influence investment decisions",
  "The impact of inflation on global economies",
  "The role of hedge funds in market speculation",
  "The rise of electric and autonomous vehicles in the automotive industry",
  "The role of cybersecurity in protecting corporate assets",
  "The emergence of NFTs and digital ownership",
  "The economic effects of pandemics on global markets",
  "The importance of intellectual property in the tech industry",
  "The influence of ESG (Environmental, Social, Governance) investing",
  "The significance of mergers and acquisitions in business strategy",
  "The rise of subscription-based business models",
  "The role of data analytics in business decision-making",
  "The economic consequences of trade wars between nations",
  "The future of remote work and digital collaboration tools",
  "The development of quantum computing in financial modeling",
  "The economic implications of climate change policies",
  "The challenges of launching a startup in emerging markets",
  "How digital payments are reducing reliance on cash transactions",
  "The role of influencer marketing in brand growth",
  "The effects of wealth inequality on economic growth",
  "The impact of monopolies and antitrust regulations in tech",
  "The shift towards sustainable investing in global finance",
  "The evolution of ride-sharing companies in urban transport",
  "How crowdfunding is changing early-stage investments",
  "The future of smart cities and urban development",
  "The impact of artificial intelligence on job displacement",
  "The challenges of global supply chain disruptions",
  "The rise of cybersecurity insurance in corporate risk management",
  "The impact of social media on stock market movements",
  "The significance of ethical AI in business decision-making",
  "The role of corporate lobbying in shaping public policy",
  "The expansion of space technology and private space exploration",
  "How biotechnology is revolutionizing healthcare and agriculture",
  "The future of personalized finance and robo-advisors",
  "The effects of tax policies on corporate growth",
  "How companies leverage big data for competitive advantage",
  "The role of microfinance in alleviating poverty in developing nations",
  "The ethical challenges of automation and workforce reduction",
  "The economic implications of universal basic income proposals",
  "The rapid growth of artificial intelligence startups",
  "How digital twins are transforming manufacturing and logistics",
  "The impact of quantum computing on financial cryptography",
  "The significance of open banking and financial APIs",
  "The future of digital identity verification and fraud prevention",
  "The economic effects of outsourcing on local job markets",
  "The influence of corporate culture on long-term profitability",
  "The role of artificial intelligence in stock market prediction",
  "How 5G technology is reshaping telecommunications and business",
  "The effects of automation on supply chain management",
  "The impact of renewable energy on global markets",
  "How social impact investing is reshaping venture capital",
  "The potential of the metaverse in digital economies",
  "The economic effects of digital currencies on traditional banking",
  "How consumer data privacy laws affect online advertising",
  "The role of government subsidies in shaping tech innovation"
];



philosophyPoliticalTopics = [
  "Plato’s Allegory of the Cave and its implications on reality and knowledge",
  "Aristotle’s concept of virtue ethics and moral character",
  "Kant’s categorical imperative and its role in moral decision-making",
  "Nietzsche’s critique of traditional morality and the concept of the Übermensch",
  "Utilitarianism and the greatest happiness principle in ethical dilemmas",
  "The philosophy of existentialism and the search for meaning",
  "Hobbes’ Leviathan and the foundation of social contract theory",
  "Locke’s theories on natural rights and government legitimacy",
  "The political philosophy of John Stuart Mill and liberal democracy",
  "Rousseau’s idea of the general will and the social contract",
  "Rawls’ theory of justice and the veil of ignorance thought experiment",
  "The ethical dilemmas of artificial intelligence and machine learning",
  "The role of Confucianism in shaping political thought in East Asia",
  "The influence of Stoicism on personal ethics and self-control",
  "The ethical debates surrounding genetic engineering and CRISPR",
  "Hume’s problem of induction and skepticism about empirical knowledge",
  "The concept of free will and determinism in philosophical thought",
  "The trolley problem and the implications of consequentialism",
  "The ethics of war and the just war theory",
  "The political implications of Machiavelli’s The Prince",
  "The philosophical foundations of anarchism and government resistance",
  "Sartre’s notion of radical freedom and responsibility",
  "The ethics of surveillance and privacy in the digital age",
  "The philosophy of mind and the question of consciousness",
  "The ethical issues of wealth inequality and distributive justice",
  "The role of feminism in contemporary political philosophy",
  "Derrida’s deconstruction and its impact on language and power structures",
  "The ethics of artificial intelligence in decision-making processes",
  "The impact of postmodernism on political and ethical discourse",
  "The paradox of tolerance in liberal societies",
  "The ethics of climate change and intergenerational justice",
  "Hegel’s dialectics and its role in historical progress",
  "The ethical considerations of whistleblowing and corporate responsibility",
  "The influence of Taoist philosophy on governance and ethics",
  "The role of nonviolent resistance in political movements",
  "The impact of Bentham’s utilitarianism on modern justice systems",
  "The philosophy of property rights and economic distribution",
  "The ethical implications of transhumanism and human enhancement",
  "The role of epistemic injustice in marginalized communities",
  "The legitimacy of civil disobedience in democratic societies",
  "The political philosophy of Karl Marx and class struggle",
  "The ethical considerations of censorship and free speech",
  "The relationship between power and corruption in political institutions",
  "The ethical dilemmas in biomedical research and experimentation",
  "The role of human rights in international relations and ethics",
  "The idea of the panopticon and the philosophy of surveillance",
  "The moral implications of drone warfare and autonomous weapons",
  "The ethical foundations of capitalism versus socialism",
  "The impact of philosophical skepticism on the pursuit of knowledge",
  "Theories of punishment and justice in criminal law",
  "The role of secular ethics in religious societies",
  "The philosophy of leadership and ethical governance",
  "The idea of distributive justice and fair wealth allocation",
  "The impact of cognitive biases on ethical reasoning",
  "The ethical concerns of genetic modification in agriculture",
  "The political philosophy of democracy versus authoritarianism",
  "The concept of cultural relativism and moral universalism",
  "The idea of personhood in ethics and moral responsibility",
  "The role of moral intuition in ethical decision-making",
  "The impact of Nietzsche’s will to power on modern thought",
  "The relationship between economic systems and moral responsibility",
  "The ethics of whistleblowing in government and corporations",
  "The influence of Eastern philosophy on Western ethical thought",
  "The ethical concerns of global capitalism and labor exploitation",
  "The philosophy of punishment and rehabilitation in the justice system",
  "The concept of legitimacy in political authority",
  "The impact of Enlightenment philosophy on modern governance",
  "The ethics of human experimentation and medical trials",
  "The intersection of law, ethics, and human dignity",
  "The implications of Machiavellian ethics in modern leadership",
  "The political ethics of populism and mass movements",
  "The role of social justice movements in ethical discourse",
  "The philosophical foundations of constitutional rights",
  "The ethical debates around assisted dying and euthanasia",
  "The moral implications of economic globalization",
  "The ethical dimensions of social media influence and misinformation"
];


artMusicFilmSportsTopics = [
  "The influence of the Harlem Renaissance on jazz and poetry",
  "The significance of Picasso’s Guernica in political art",
  "The impact of The Beatles on popular music evolution",
  "The role of Serena Williams in transforming women’s tennis",
  "The rise of street art through Banksy’s work",
  "The global influence of K-pop and BTS",
  "The effect of the Oscars on the film industry",
  "The fashion revolution of Coco Chanel",
  "The significance of Michael Jordan’s career in globalizing the NBA",
  "The storytelling techniques of Alfred Hitchcock in suspense films",
  "The rise of hip-hop culture and its societal influence",
  "The Golden Age of Hollywood and its impact on cinema",
  "The influence of ballet on modern dance movements",
  "The role of video games as an artistic medium",
  "The rise of anime and manga in global entertainment",
  "The evolution of electronic music and its cultural impact",
  "The historical significance of The Renaissance in visual arts",
  "The impact of social media on contemporary music artists",
  "The influence of Broadway musicals on global theater trends",
  "The development of method acting in film and theater",
  "The importance of folk music in cultural preservation",
  "The impact of streaming services on the music industry",
  "The role of fashion as a form of political expression",
  "The cultural influence of The Rolling Stones in rock music",
  "The artistry behind Studio Ghibli films and their narratives",
  "The portrayal of gender roles in classic Hollywood films",
  "The aesthetic and cultural impact of Art Deco architecture",
  "The legacy of Andy Warhol in pop art and media culture",
  "The role of hip-hop in political activism",
  "The significance of Shakespeare’s plays in modern storytelling",
  "The fusion of classical and modern music in film scores",
  "The technological advancements in CGI and their effects on filmmaking",
  "The cultural importance of streetwear in contemporary fashion",
  "The use of symbolism in surrealist paintings",
  "The controversy surrounding performance-enhancing drugs in sports",
  "The influence of African drumming on contemporary world music",
  "The transition from silent films to talkies in early cinema",
  "The impact of the feminist movement on fashion trends",
  "The artistic significance of Michelangelo’s Sistine Chapel frescoes",
  "The representation of minorities in major film industries",
  "The influence of classical composers on modern film scores",
  "The economic impact of global sporting events like the Olympics",
  "The role of street photography in documenting urban life",
  "The relationship between graffiti art and political protest movements",
  "The importance of Renaissance perspective techniques in visual arts",
  "The rise of viral internet challenges and their impact on pop culture",
  "The connection between skateboarding and street fashion trends",
  "The use of digital art in redefining traditional painting techniques",
  "The rise of independent cinema in contrast to Hollywood blockbusters",
  "The historical significance of breakdancing in hip-hop culture",
  "The aesthetic and thematic evolution of superhero films",
  "The integration of indigenous art into contemporary design",
  "The role of photography in war journalism and activism",
  "The evolution of gothic architecture and its cultural legacy",
  "The significance of sports diplomacy in international relations",
  "The evolution of dance styles in response to cultural shifts",
  "The rise of sustainable fashion and ethical production practices",
  "The role of literature in inspiring film adaptations",
  "The use of minimalism in modern architecture and interior design",
  "The impact of rock ‘n’ roll on social and political change",
  "The incorporation of artificial intelligence in music composition",
  "The influence of punk fashion on rebellious youth movements",
  "The artistic and technical innovation of Pixar’s animated films",
  "The representation of mental health in contemporary theater",
  "The influence of Harlem ball culture on mainstream fashion trends",
  "The role of sports as a catalyst for racial and gender equality",
  "The use of satire and comedy in political cartoons",
  "The integration of classical music in modern experimental genres",
  "The global influence of Bollywood cinema on entertainment trends",
  "The impact of jazz improvisation on contemporary music production",
  "The role of sports analytics in revolutionizing athletic performance",
  "The intersection of architecture and environmental sustainability"
];


famousBiographies = [
  "The life and scientific achievements of Albert Einstein",
  "The political philosophy and leadership of Mahatma Gandhi",
  "The rise of Napoleon Bonaparte and his impact on Europe",
  "The legacy of Winston Churchill during World War II",
  "The revolutionary activism of Nelson Mandela in South Africa",
  "The scientific discoveries of Marie Curie in radioactivity",
  "The pioneering work of Ada Lovelace in early computing",
  "The exploration and expeditions of Marco Polo",
  "The artistic genius of Leonardo da Vinci in multiple disciplines",
  "The civil rights activism of Martin Luther King Jr.",
  "The contributions of Charles Darwin to evolutionary theory",
  "The role of Abraham Lincoln in preserving the Union",
  "The poetic and philosophical impact of Maya Angelou",
  "The political legacy of Theodore Roosevelt in American history",
  "The humanitarian work of Mother Teresa in global aid",
  "The engineering and innovation of Nikola Tesla",
  "The military strategy and conquests of Alexander the Great",
  "The revolutionary ideas of Karl Marx in economic philosophy",
  "The political reforms of Franklin D. Roosevelt during the Great Depression",
  "The contributions of Isaac Newton to physics and mathematics",
  "The life and artistic influence of Vincent van Gogh",
  "The leadership and legacy of Julius Caesar in Rome",
  "The literary brilliance of William Shakespeare",
  "The advancements in civil rights by Rosa Parks",
  "The influential psychological theories of Sigmund Freud",
  "The visionary impact of Steve Jobs on technology",
  "The musical genius of Ludwig van Beethoven",
  "The human rights activism of Malala Yousafzai",
  "The impact of Pablo Picasso on modern art",
  "The space exploration legacy of Neil Armstrong",
  "The scientific breakthroughs of Galileo Galilei",
  "The political leadership of Margaret Thatcher in Britain",
  "The life and discoveries of Louis Pasteur in microbiology",
  "The revolutionary role of Che Guevara in Latin America",
  "The influence of Confucius on Eastern philosophy",
  "The cultural impact of Oprah Winfrey as a media mogul",
  "The global influence of Muhammad Ali in sports and activism",
  "The presidency and policies of John F. Kennedy",
  "The humanitarian work and legacy of Princess Diana",
  "The philosophical contributions of Aristotle to Western thought",
  "The leadership and governance of Catherine the Great",
  "The engineering brilliance of Thomas Edison",
  "The feminist writings and activism of Simone de Beauvoir",
  "The scientific discoveries of Johannes Kepler in astronomy",
  "The medical innovations of Florence Nightingale in nursing",
  "The revolutionary strategies of Vladimir Lenin in Russia",
  "The pioneering aviation achievements of Amelia Earhart",
  "The political philosophy and writings of John Locke",
  "The impact of Frida Kahlo’s art on feminism and identity",
  "The global influence of Muhammad in Islamic teachings",
  "The presidency and social programs of Lyndon B. Johnson",
  "The literary brilliance of Jane Austen in English literature",
  "The leadership of Dwight D. Eisenhower in World War II",
  "The contributions of Stephen Hawking to theoretical physics",
  "The influence of Coco Chanel on modern fashion",
  "The fight against apartheid led by Desmond Tutu",
  "The philosophical insights of Jean-Jacques Rousseau",
  "The athletic achievements of Michael Jordan",
  "The rise of Elon Musk as an entrepreneur and innovator",
  "The musical legacy of Wolfgang Amadeus Mozart",
  "The spiritual leadership of Dalai Lama in Tibetan Buddhism",
  "The human rights activism of Eleanor Roosevelt",
  "The pioneering work of Jonas Salk in polio vaccination",
  "The political vision of Woodrow Wilson in world diplomacy",
  "The poetic works and activism of Langston Hughes",
  "The scientific genius of Richard Feynman in quantum physics",
  "The impact of Helen Keller as a disability rights advocate",
  "The architectural innovations of Frank Lloyd Wright",
  "The rise of Jeff Bezos and the creation of Amazon",
  "The radical politics of Malcolm X in the civil rights movement",
  "The explorations of Christopher Columbus in the New World",
  "The military tactics and leadership of Ulysses S. Grant",
  "The literary influence of J.R.R. Tolkien in fantasy writing",
  "The presidency of Barack Obama and his political legacy",
  "The contributions of Claude Monet to the Impressionist movement",
  "The mathematical genius of Alan Turing and computer science",
  "The artistic and cultural impact of Michelangelo",
  "The humanitarian efforts of Bill Gates in global health initiatives",
  "The filmmaking legacy of Steven Spielberg in Hollywood",
  "The scientific achievements of Rosalind Franklin in DNA research",
  "The cultural impact of Walt Disney in entertainment",
  "The presidency and leadership of George Washington",
  "The social impact of Jane Goodall’s work with chimpanzees",
  "The advocacy of Marsha P. Johnson in the LGBTQ+ movement",
  "The economic theories of John Maynard Keynes and their impact",
  "The contributions of Rachel Carson to environmental awareness",
  "The technological innovations of Grace Hopper in programming",
  "The philosophical influence of Hannah Arendt on political thought",
  "The pioneering feminist activism of bell hooks",
  "The groundbreaking work of Katherine Johnson in space exploration",
  "The social justice activism of Cesar Chavez in labor rights",
  "The contributions of Mae Jemison as the first Black woman in space",
  "The impact of Temple Grandin on autism advocacy and animal science",
  "The literary achievements of Octavia Butler in science fiction",
  "The medical breakthroughs of Virginia Apgar in newborn care",
  "The role of Wangari Maathai in sustainable environmental efforts",
  "The political activism of Shirley Chisholm in U.S. history",
  "The influence of Buckminster Fuller on sustainable architecture",
  "The advocacy of Harriet Tubman in the Underground Railroad",
  "The leadership of Ellen Johnson Sirleaf as Africa’s first female president",
  "The groundbreaking research of Barbara McClintock in genetics",
  "The investigative journalism of Ida B. Wells in anti-lynching efforts",
  "The scientific contributions of Dorothy Crowfoot Hodgkin in chemistry",
  "The impact of Nikolaas Tinbergen on animal behavior studies",
  "The activism of Dolores Huerta in labor rights and civil justice",
  "The pioneering work of Sylvia Earle in ocean exploration",
  "The influence of Hypatia of Alexandria in mathematics and philosophy",
  "The advocacy of Mary Seacole in battlefield nursing",
  "The groundbreaking cancer research of Marie Maynard Daly",
  "The political leadership of Golda Meir as Israel’s prime minister",
  "The role of Clara Barton in founding the American Red Cross",
  "The economic theories of Amartya Sen on social welfare",
  "The impact of Gertrude B. Elion in pharmaceutical advancements",
  "The scientific exploration of Ernest Shackleton in Antarctica",
  "The literary contributions of Zora Neale Hurston in African American culture",
  "The role of Niels Bohr in quantum mechanics",
  "The impact of Edith Clarke on electrical engineering",
  "The innovations of Rachel Parsons in women’s rights and engineering",
  "The global health initiatives of Paul Farmer in medical equity",
  "The breakthroughs of Nettie Stevens in discovering sex chromosomes",
  "The contributions of Lise Meitner in nuclear physics",
  "The leadership of Sequoyah in developing the Cherokee syllabary",
  "The feminist activism of Emmeline Pankhurst in securing voting rights",
  "The social reforms led by Jane Addams in urban poverty alleviation",
  "The agricultural advancements of George Washington Carver",
  "The role of Henrietta Lacks’ cells in medical research",
  "The contributions of Alan Lomax in preserving folk music traditions",
  "The advocacy of Elizabeth Blackwell as the first female doctor in the U.S.",
  "The pioneering educational work of Maria Montessori",
  "The influence of Caroline Herschel in astronomy and comet discoveries",
  "The political leadership of Benazir Bhutto as Pakistan’s first female prime minister",
  "The environmental activism of Chico Mendes in Amazon rainforest preservation",
  "The role of Vera Rubin in confirming dark matter’s existence",
  "The impact of Rosalind Franklin’s work on DNA structure discovery",
  "The architectural innovations of Zaha Hadid in modern design",
  "The political impact of Shirley Ann Jackson in nuclear policy and physics",
  "The influence of Ada Yonath in ribosome research and medicine",
  "The discoveries of Tu Youyou in malaria treatment",
  "The advocacy of Bessie Coleman as the first Black female aviator",
  "The scientific impact of Dorothy Vaughan in early computing and NASA",
  "The role of Hedy Lamarr in inventing frequency-hopping technology",
  "The entrepreneurial influence of Madam C.J. Walker in cosmetics",
  "The artistic contributions of Alma Thomas in abstract painting",
  "The literary impact of Nella Larsen in the Harlem Renaissance",
  "The impact of Ellen Ochoa as the first Hispanic woman in space",
  "The investigative journalism of Nellie Bly in exposing social injustices",
  "The groundbreaking primatology research of Dian Fossey",
  "The medical advancements led by Alice Augusta Ball in leprosy treatment",
  "The activism of Fannie Lou Hamer in the civil rights movement",
  "The innovations of Beulah Louise Henry in patenting household technologies",
  "The role of Frances Perkins as the first female U.S. cabinet member",
  "The environmental contributions of Sylvia Earle in ocean conservation",
  "The impact of Mae Mallory in the civil rights and education movement",
  "The scientific contributions of Chien-Shiung Wu in physics research",
  "The influence of Margaret Hamilton in developing Apollo mission software",
  "The leadership of Harriet Ann Boyd Hawes in archaeological discoveries",
  "The groundbreaking engineering work of Edith Clarke in power transmission",
  "The role of Lillian Moller Gilbreth in industrial engineering and psychology",
  "The innovations of Stephanie Kwolek in developing Kevlar technology",
  "The mathematical advancements of Mary Cartwright in nonlinear systems",
  "The medical achievements of Virginia Apgar in infant health assessment"
];


modernTopicsAndFun = [
  "The influence of AI-generated music on the future of the music industry",
  "The impact of TikTok on reshaping short-form storytelling and entertainment",
  "The ethical implications of AI-created art and its effect on human creativity",
  "The growing influence of esports as a legitimate professional career path",
  "The rise of solo travel culture and its impact on global tourism",
  "The psychology behind viral internet trends and why they spread",
  "The cultural impact of video game adaptations in film and TV",
  "The effect of influencer culture on brand loyalty and marketing strategies",
  "The rise of space tourism and the future of commercial spaceflight",
  "The impact of ‘quiet quitting’ and workplace culture shifts post-pandemic",
  "The influence of digital detox trends on mental health and social behaviors",
  "The growing popularity of virtual pets and AI companions in modern life",
  "The return of Y2K fashion and the nostalgia cycle in pop culture",
  "The future of immersive concerts using virtual reality and holograms",
  "The debate over whether video games should be considered an art form",
  "The psychology of binge-watching and how streaming changed storytelling",
  "The impact of true crime obsession on public perceptions of justice",
  "The role of nostalgia in reviving old franchises like Star Wars and Marvel",
  "The rise of AI-generated social media influencers and digital personalities",
  "The significance of online communities like Reddit and Discord in modern discourse",
  "The influence of cyberpunk themes in tech innovation and digital culture",
  "The role of music festivals in shaping youth culture and social movements",
  "The future of ethical hacking and its role in cybersecurity",
  "The impact of AI-generated storytelling in video games and literature",
  "The ethical dilemmas of deepfake celebrity endorsements and misinformation",
  "The role of Twitch and YouTube streaming in shaping modern entertainment",
  "The social impact of VR social spaces and the rise of digital hangouts",
  "The cultural impact of anime and manga on Western storytelling and media",
  "The effects of fan theories on how audiences engage with storytelling",
  "The influence of K-dramas on global television trends",
  "The future of cinema in an era dominated by streaming services",
  "The rise of micro-celebrities and how anyone can become famous online",
  "The shifting perspectives on traditional college education in the digital age",
  "The implications of smart glasses and augmented reality in everyday life",
  "The cultural impact of speedrunning and the competitive gaming community",
  "The rise of AI-powered personal assistants and their potential benefits/drawbacks",
  "The intersection of gaming and fitness with VR-based exercise programs",
  "The resurgence of board games and in-person social gaming culture",
  "The growing appeal of low-fi music and its impact on mental focus",
  "The influence of algorithm-driven entertainment recommendations on personal taste",
  "The role of online book communities like BookTok in reviving literature trends",
  "The future of digital ownership and the metaverse economy",
  "The psychological effects of ASMR content and why people find it relaxing",
  "The impact of virtual influencers on brand marketing and social media trends",
  "The debate around AI-generated fanfiction and intellectual property rights",
  "The psychology behind ‘main character energy’ and self-perception online",
  "The role of crowdfunding platforms in launching creative projects and businesses",
  "The ethical considerations of AI-generated journalism and automated news writing",
  "The impact of wearable technology on health tracking and personal wellness",
  "The potential future of hyperloop transportation and high-speed travel",
  "The evolving role of robots and automation in fast food and service industries",
  "The influence of aesthetic-driven social media like Pinterest and Tumblr on creativity",
  "The impact of AI-driven chatbots and emotional support AI on mental health care",
  "The implications of biohacking and personalized medicine for longevity",
  "The role of fan fiction communities in redefining traditional storytelling",
  "The impact of nostalgia-driven marketing in modern advertising campaigns",
  "The intersection of mindfulness and productivity in an era of constant connectivity",
  "The psychology behind the ‘fear of missing out’ (FOMO) and social behaviors",
  "The debate over digital hoarding and the environmental impact of data storage",
  "The impact of collaborative video games on teamwork and leadership skills",
  "The rise of AI voice cloning technology and its implications for media and security",
  "The evolution of AI-generated memes and humor in internet culture",
  "The effect of AI-generated movie trailers and predictive film success models",
  "The growing appeal of ‘cottagecore’ and escapism-driven online subcultures",
  "The influence of hyper-personalized AI recommendations on personal preferences",
  "The role of streaming platforms in reviving niche musical genres",
  "The impact of experimental indie games on the future of interactive storytelling",
  "The ethical debate over AI-generated ‘deep nostalgia’ for historical figures",
  "The psychology of online rage culture and its impact on digital communities",
  "The implications of ‘smart tattoos’ and biometric wearable technology",
  "The role of AI in assisting with creative endeavors like painting and composing music",
  "The psychological impact of virtual pets in digital spaces like the Metaverse",
  "The influence of online personality tests and astrology in shaping self-identity",
  "The resurgence of drive-in theaters and alternative cinema experiences post-pandemic",
  "The role of online petitions and grassroots activism in influencing political change",
  "The rise of ‘slow fashion’ and sustainable consumer choices in youth culture",
  "The effects of AI-driven voice assistants on language learning and communication",
  "The impact of climate anxiety on young people's lifestyle and career choices",
  "The rise of AI-powered NPCs in open-world video games and their storytelling potential",
  "The ethical questions surrounding AI-generated celebrity holograms in entertainment",
  "The impact of artificial intelligence on job markets and ethics",
  "The role of social media in shaping political opinions among Gen Z",
  "The impact of climate change policies on global economies and migration",
  "The ethical dilemmas of deepfake technology in media and entertainment",
  "The portrayal of mental health in modern video games like Celeste and Hellblade",
  "The rise of esports and its influence on traditional sports and entertainment",
  "The role of influencers in modern advertising and consumer trust",
  "The ethics of genetic engineering and human enhancement",
  "The growing impact of AI-generated content on creative industries",
  "The social implications of virtual reality and the metaverse",
  "The psychological effects of doomscrolling and digital addiction",
  "The influence of global streaming platforms on cultural homogenization",
  "The representation of diverse identities in contemporary superhero films",
  "The impact of cryptocurrency and NFTs on digital economies",
  "The role of citizen journalism in holding governments accountable",
  "The ethical concerns of automation and the future of human labor",
  "The portrayal of gender and sexuality in modern fantasy literature",
  "The moral dilemmas of space colonization and privatization",
  "The rise of book banning and censorship in modern education",
  "The impact of fast fashion on global labor and environmental sustainability",
  "The historical significance of meme culture in modern political discourse",
  "The effects of algorithm-driven content on social division and polarization",
  "The role of fandoms in shaping modern storytelling and entertainment franchises",
  "The ethical questions surrounding facial recognition technology and privacy",
  "The rise of true crime media and its impact on public perception of justice",
  "The influence of K-pop and globalized music industries on cultural diplomacy",
  "The portrayal of dystopian futures in contemporary science fiction films",
  "The resurgence of cyberpunk aesthetics in gaming and tech culture",
  "The ethics of cancel culture and the limits of online accountability",
  "The potential of biotech in solving global food insecurity",
  "The portrayal of climate anxiety in modern literature and media",
  "The impact of deep-space exploration on humanity’s self-perception",
  "The psychological effects of constant online validation in younger generations",
  "The historical evolution of hacking culture and its portrayal in media",
  "The influence of global pop culture on reshaping national identities",
  "The representation of neurodivergent characters in contemporary storytelling",
  "The power dynamics of social media monopolies in shaping public discourse",
  "The effects of generational shifts on workplace culture and expectations",
  "The environmental implications of mass data storage and digital consumption",
  "The rise of ethical fashion movements and slow consumerism",
  "The moral implications of AI-generated deep relationships and chatbots",
  "The gamification of education and its impact on student learning and engagement",
  "The role of nostalgia in marketing and modern media consumption trends",
  "The increasing role of government regulation in social media platforms",
  "The potential of virtual influencers and AI-created personalities in entertainment",
  "The debate around universal basic income in response to automation",
  "The influence of post-pandemic social changes on urban planning and housing",
  "The impact of online conspiracy theories on democratic institutions",
  "The emergence of AI-driven journalism and its effect on traditional reporting",
  "The ethical concerns of microtransactions and loot boxes in gaming",
  "The redefinition of masculinity and gender expectations in contemporary media",
  "The role of nostalgia in shaping modern remakes and reboots in Hollywood",
  "The potential risks and rewards of brain-computer interfaces",
  "The increasing crossover between gaming, literature, and film storytelling techniques",
  "The shifting narratives around artificial intelligence in sci-fi films and books",
  "The role of grassroots activism in the digital age",
  "The rise of solarpunk literature as an alternative to dystopian narratives",
  "The evolving nature of online identities and digital personas",
  "The effects of short-form video content on audience attention spans",
  "The ethics of biohacking and citizen-led genetic research",
  "The portrayal of futuristic cities in science fiction and their real-world implications"
];




